import Foundation
import WebKit
import Irgo  // Generated by gomobile bind

/// Main bridge class that connects iOS to the Go framework
public class IrgoBridge: NSObject {
    public static let shared = IrgoBridge()

    private var webView: WKWebView?
    private var schemeHandler: IrgoSchemeHandler?

    private override init() {
        super.init()
        // Initialize the Go bridge
        MobileInitialize()
    }

    /// Configure the bridge with a WebView
    public func configure(webView: WKWebView) {
        self.webView = webView
    }

    /// Check if the bridge is ready
    public var isReady: Bool {
        return MobileIsReady()
    }

    /// Handle an HTTP request and return the response
    public func handleRequest(
        method: String,
        url: String,
        headers: [String: String] = [:],
        body: Data? = nil
    ) -> IrgoResponse {
        let headersJSON = try? JSONSerialization.data(withJSONObject: headers)
        let headersString = headersJSON.flatMap { String(data: $0, encoding: .utf8) } ?? "{}"

        guard let response = MobileHandleRequest(method, url, headersString, body) else {
            return IrgoResponse(status: 500, headers: [:], body: Data())
        }

        return IrgoResponse(from: response)
    }

    /// Get the initial HTML page content
    public func renderInitialPage() -> String {
        return MobileRenderInitialPage()
    }

    /// Shutdown the bridge
    public func shutdown() {
        MobileShutdown()
    }
}

/// Swift-friendly response wrapper
public struct IrgoResponse {
    public let status: Int
    public let headers: [String: String]
    public let body: Data

    public var bodyString: String {
        return String(data: body, encoding: .utf8) ?? ""
    }

    init(status: Int, headers: [String: String], body: Data) {
        self.status = status
        self.headers = headers
        self.body = body
    }

    init(from response: MobileResponse) {
        self.status = Int(response.status)
        self.body = response.body ?? Data()

        // Parse headers from JSON
        if let headersData = response.headers.data(using: .utf8),
           let parsed = try? JSONSerialization.jsonObject(with: headersData) as? [String: String] {
            self.headers = parsed
        } else {
            self.headers = [:]
        }
    }
}
